POST /projects/1/comments
Host: localhost:8082
Content-Type: application/json

{
  "commentContent": 2,
  "accountId": "user2"
}

###

GET /projects/1/taskTags/1
Host: localhost:8082

###

DELETE /projects/1/taskTags/1
Host: localhost:8082