POST /projects/9/milestones
Host: localhost:8082
Content-Type: application/json

{
  "milestoneContent" : "마일스톤9-2",
  "milestoneStartAt" : "2023-06-02",
  "milestoneEndAt" : "2023-06-06"
}

###

GET /projects/3/milestones
Host: localhost:8082

###

GET /projects/2/milestones/10
Host: localhost:8082

###

DELETE /projects/3/milestones/9
Host: localhost:8082