POST /projects/1/milestones
Host: localhost:8082
Content-Type: application/json

{
  "milestoneContent" : "마일스톤2",
  "milestoneStartAt" : "2023-06-02",
  "milestoneEndAt" : "2023-06-06"
}

###

GET /projects/1/milestones
Host: localhost:8082

###

GET /projects/1/milestones/2
Host: localhost:8082

###

DELETE /projects/1/milestones/1
Host: localhost:8082