POST /projects
Host: localhost:8082
Content-Type: application/json

{
  "projectAdminId" : "user4",
  "projectName" : "project4",
  "projectDescription" : "4번프로젝트"
}

###
GET /projects/1/members/user1
Host: localhost:8082
Content-Type: application/json

###

GET /projects
Host: localhost:8082

###

GET /projects/1
Host: localhost:8082

###

PATCH /projects/1
Host: localhost:8082
Content-Type: application/json

{
  "projectStatus" : "SLEEP"
}