POST /projects/1/tasks
Host: localhost:8082
Content-Type: application/json

{
  "taskTitle" : "야호",
  "taskContent" :"업무 내용4" ,
  "taskManagerId" : "user2",
  "taskRegisterId" : "user2",
  "taskStartAt" : "2023-06-01",
  "taskEndAt" : "2023-06-02",
  "milestoneId": 1
}

###

GET /projects/1/tasks
Host: localhost:8082

###

GET /projects/1/tasks/5
Host: localhost:8082

###

PATCH /projects/1/tasks/4
Host: localhost:8082
Content-Type: application/json

{
  "taskManagerId": "user7"
}

###

DELETE /projects/1/tasks/6
Host: localhost:8082